spring.application.name=uptime

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sentinel}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sentinel}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sentinel}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=${JWT_SECRET:change-me-local-dev-secret-change-me}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS:3000000}

whois.api.key=${WHOIS_API_KEY:}
whois.api.url=${WHOIS_API_URL:https://www.whoisxmlapi.com/whoisserver/WhoisService}

post.url.go=${GO_PROBE_URL:http://localhost:8081/}
frontend.url=${FRONTEND_URL:http://localhost:3000}
ai.service.url=${AI_SERVICE_URL:http://localhost:8090}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:sentinel-spring}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
sentinel.kafka.monitor-lifecycle-topic=${MONITOR_LIFECYCLE_TOPIC:sentinel.monitor.lifecycle}
sentinel.kafka.monitor-checks-topic=${MONITOR_CHECKS_TOPIC:sentinel.monitor.checks}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.from=${MAIL_FROM:no-reply@sentinel.local}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:false}
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dev-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dev-google-client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
